### ISSUE TITLE
What is the wiring scheme for this

### ISSUE THREAD

**Issue by ghost** [20after4/micropython-esp32-wrover-lcd#2]
Hi,

I am trying to implement this but cannot find any example on which pins to attach the display to, especially since there are the ones with 16 pins and then those of the 4 pin i2c backpack.

Coulkd you please provide a sample file for this?

Many thanks!

**Comment by ghost** [comment]
Sorry,  I figured this out.

**Comment by heikkihietala** [comment]
An solution was found.
